#!/bin/bash -l
#SBATCH --job-name="0p1coverage_1001bp_fasta_bias"
#SBATCH -o 0p1coverage_1001bp_fasta_bias.o
#SBATCH -e 0p1coverage_1001bp_fasta_bias.e

#########################################################################################
reference=/path/ARS-UCD1.2/GCF_002263795.1_ARS-UCD1.2_refseq_chrids.fa
lsk_bed=/path/
rbk_bed=/path/
lsk_fasta=/path/
rbk_fasta=/path/
lsk_1001_cleavage=/path/
rbk_1001_cleavage=/path/

#########################################################################################
module load anaconda3
module load samtools
module load bedtools/2.30.0-gcc-10.3.0

#########################################################################################
### extract fasta reads for LSK data
cd $lsk_bed
source activate seqkit
for file in *_plus.bed
do
	echo "now is processing $file"
	awk '{$2 = $2 - 500; print}' $file | \
	awk '{OFS="\t";} {$3 = $2 + 1001; print}' | \
	awk -v threshold=31 '($2 >= 0) && ($3 >= 0) && (($3 - $2) >= threshold)' | \
	fastaFromBed -fi $reference -bed stdin -fo stdout | \
	seqkit seq -u > ${file%%.*}_1001bp.fasta
done

for file in *_minus.bed
do
	echo "now is processing $file"
	awk '{$2 = $3 - 501; print}' $file | \
	awk '{OFS="\t";} {$3 = $2 + 1001; print}' | \
	awk -v threshold=31 '($2 >= 0) && ($3 >= 0) && (($3 - $2) >= threshold)' | \
	fastaFromBed -fi $reference -bed stdin -fo stdout | \
	seqkit seq -u > ${file%%.*}_1001bp.fasta
done

for file in *_minus_1001bp.fasta
do
	seqkit seq --complement --reverse -v -t DNA $file > ${file%%.*}_RC.fasta
done

cat *_plus_1001bp.fasta *_1001bp_RC.fasta > LSK_TSU_0p1_1001bp.fasta
cp *_plus_1001bp.fasta *_1001bp_RC.fasta LSK_TSU_0p1_1001bp.fasta $lsk_1001_cleavage
mv *.fasta $lsk_fasta

#########################################################################################
### extract fasta reads for RBK data
cd $rbk_bed
source activate seqkit
for file in *_plus.bed
do
	echo "now is processing $file"
	awk '{$2 = $2 - 500; print}' $file | \
	awk '{OFS="\t";} {$3 = $2 + 1001; print}' | \
	awk -v threshold=31 '($2 >= 0) && ($3 >= 0) && (($3 - $2) >= threshold)' | \
	fastaFromBed -fi $reference -bed stdin -fo stdout | \
	seqkit seq -u > ${file%%.*}_1001bp.fasta
done

for file in *_minus.bed
do
	echo "now is processing $file"
	awk '{$2 = $3 - 501; print}' $file | \
	awk '{OFS="\t";} {$3 = $2 + 1001; print}' | \
	awk -v threshold=31 '($2 >= 0) && ($3 >= 0) && (($3 - $2) >= threshold)' | \
	fastaFromBed -fi $reference -bed stdin -fo stdout | \
	seqkit seq -u > ${file%%.*}_1001bp.fasta
done

for file in *_minus_1001bp.fasta
do
	seqkit seq --complement --reverse -v -t DNA $file > ${file%%.*}_RC.fasta
done

cat *_plus_1001bp.fasta *_1001bp_RC.fasta > RBK_TSU_0p1_1001bp.fasta
cp *_plus_1001bp.fasta *_1001bp_RC.fasta RBK_TSU_0p1_1001bp.fasta $rbk_1001_cleavage
mv *.fasta $rbk_fasta

#########################################################################################
### Percentage calculation using python script

cd /scratch/project/genoepic_rumen
python Nucleotides_Percentage_v3.py --path $lsk_1001_cleavage --long 1001
python Nucleotides_Percentage_v3.py --path $rbk_1001_cleavage --long 1001
