#!/bin/bash -l
#SBATCH --job-name="nanopolish_mcaller_anabaena_fibrobacter"
#SBATCH -o nanopolish_mcaller_anabaena_fibrobacter.o
#SBATCH -e nanopolish_mcaller_anabaena_fibrobacter.e

#########################################################
fastq_path=/path/

anabaena_ref=/path/anabaena_sp_YBS01_ref/GCF_009498015.1_ASM949801v1_genomic.fna
anabaena_mapping=/path/
anabaena_eventalign=/path/
anabaena_mcaller_tsv=/path/
anabaena_mcaller_eventalign=/path/

fibrobacter_ref=/path/fibrobacter_succinogenes_ref/GCF_000146505.1_ASM14650v1_genomic.fna
fibrobacter_mapping=/path/
fibrobacter_eventalign=/path/
fibrobacter_mcaller_tsv=/path/
fibrobacter_mcaller_eventalign=/path/

model_path=/path/mCaller/
mCaller=/path/mCaller.py
makebed=/path/make_bed.py

#########################################################
### minimap2 mapping
module load anaconda3
source activate minimap2

### anabaena
cd $fastq_path
for file in *.fastq;
do
	minimap2 -ax map-ont $anabaena_ref \
	$file -t 22 -o $anabaena_mapping/${file%%.*}.sam
done

### fibrobacter
cd $fastq_path
for file in *.fastq;
do
	minimap2 -ax map-ont $fibrobacter_ref \
	$file -t 22 -o $fibrobacter_mapping/${file%%.*}.sam
done

#########################################################
### samtools indexing
module load samtools

### anabaena
cd $anabaena_mapping
for file in *.sam;
do
	samtools view -bS $file | samtools sort -T /tmp/${file%%.*}.sorted -o ${file%%.*}.sorted.bam
	samtools index ${file%%.*}.sorted.bam
done

### fibrobacter
cd $fibrobacter_mapping
for file in *.sam;
do
	samtools view -bS $file | samtools sort -T /tmp/${file%%.*}.sorted -o ${file%%.*}.sorted.bam
	samtools index ${file%%.*}.sorted.bam
done

#########################################################
### nanopolish eventalign
source activate nanopolish

### anabaena
cd $anabaena_mapping
for file in *.sam; 
do
	filename=${file%%.*}
	nanopolish eventalign -t 22 --scale-events -n -r $fastq_path/${filename}.fastq -b $anabaena_mapping/${filename}.sorted.bam -g $anabaena_ref \
	> $anabaena_eventalign/${filename}.eventalign.tsv
done

### fibrobacter
cd $fibrobacter_mapping
for file in *.sam; 
do
	filename=${file%%.*}
	nanopolish eventalign -t 22 --scale-events -n -r $fastq_path/${filename}.fastq -b $fibrobacter_mapping/${filename}.sorted.bam -g $fibrobacter_ref \
	> $fibrobacter_eventalign/${filename}.eventalign.tsv
done

#########################################################
### mcaller detection
source activate mcaller

### anabaena
cd $anabaena_eventalign
for file in *.eventalign.tsv; 
do
	filename=${file%%.*}
	python $mCaller -m GATC \
	-r $anabaena_ref -d $model_path/r95_twobase_model_NN_6_m6A.pkl \
	-e $anabaena_eventalign/${filename}.eventalign.tsv -f $fastq_path/${filename}.fastq -b A
done

### fibrobacter
cd $fibrobacter_eventalign
for file in *.eventalign.tsv; 
do
	filename=${file%%.*}
	python $mCaller -m GATC \
	-r $fibrobacter_ref -d $model_path/r95_twobase_model_NN_6_m6A.pkl \
	-e $fibrobacter_eventalign/${filename}.eventalign.tsv -f $fastq_path/${filename}.fastq -b A
done

#########################################################
### tansform the mcaller output file
### anabaena
cd $anabaena_eventalign
mv *.eventalign.diffs.6 $anabaena_mcaller_eventalign

cd $anabaena_mcaller_eventalign
for file in lsk_*.eventalign.*;
do
    awk -v filename=${file%%.*} -v kit="Ligation_kit" 'BEGIN{FS=OFS="\t"}''{print filename, kit, $0}' $file > ${file%%.*}.tsv
done

for file in rbk_*.eventalign.*;
do
    awk -v filename=${file%%.*} -v kit="Rapid_kit" 'BEGIN{FS=OFS="\t"}''{print filename, kit, $0}' $file > ${file%%.*}.tsv
done

cat lsk_*.tsv > $anabaena_mcaller_tsv/lsk_anabaena_sp_YBS01.tsv
cat rbk_*.tsv > $anabaena_mcaller_tsv/rbk_anabaena_sp_YBS01.tsv

### fibrobacter
cd $fibrobacter_eventalign
mv *.eventalign.diffs.6 $fibrobacter_mcaller_eventalign

cd $fibrobacter_mcaller_eventalign
for file in lsk_*.eventalign.*;
do
    awk -v filename=${file%%.*} -v kit="Ligation_kit" 'BEGIN{FS=OFS="\t"}''{print filename, kit, $0}' $file > ${file%%.*}.tsv
done

for file in rbk_*.eventalign.*;
do
    awk -v filename=${file%%.*} -v kit="Rapid_kit" 'BEGIN{FS=OFS="\t"}''{print filename, kit, $0}' $file > ${file%%.*}.tsv
done

cat lsk_*.tsv > $fibrobacter_mcaller_tsv/lsk_fibrobacter_succinogenes.tsv
cat rbk_*.tsv > $fibrobacter_mcaller_tsv/rbk_fibrobacter_succinogenes.tsv
