#!/bin/bash -l
#SBATCH --job-name="kraken2_db_build_15052024"
#SBATCH -o kraken2_db_build_15052024.o
#SBATCH -e kraken2_db_build_15052024.e

################################################################
module load anaconda3
source activate kraken2

################################################################
DBNAME=/path/

################################################################
## Install a taxonomy
kraken2-build --download-taxonomy --threads 12 --db $DBNAME

################################################################
## Install one or more reference libraries
kraken2-build --download-library bacteria --threads 12 --db $DBNAME
kraken2-build --download-library archaea --threads 12 --db $DBNAME
kraken2-build --download-library fungi --threads 12 --db $DBNAME
kraken2-build --download-library protozoa --threads 12 --db $DBNAME

################################################################
## Build the database
kraken2-build --build --threads 12 --db $DBNAME