#!/bin/bash -l
#SBATCH --job-name="rumen_fastq_base_number_sup"
#SBATCH -o rumen_fastq_base_number_sup.o
#SBATCH -e rumen_fastq_base_number_sup.e

##############################################################
nanofilt_dir_seq_fa=/path/fa/nanofilt
nanofilt_dir_seq_hac=/path/hac/nanofilt
nanofilt_dir_seq_sup=/path/sup/nanofilt

nanofilt_dir_dna_fa=/path/fa/nanofilt 
nanofilt_dir_dna_hac=/path/hac/nanofilt
nanofilt_dir_dna_sup=/path/sup/nanofilt

stats_dir=/path/

##############################################################
### calculate base number
module load anaconda3
source activate seqkit

cd $stats_dir

### calculate base number for seq data
echo -e "sample_id\textraction_kit\tsequencing_kit\tbasecall_mode\tlocation\traw_bases\tafter_bases\ttrim_bases" > rumen_base_num_stats_sup.tsv
for i in fa hac sup; do
    raw_fastq_dir=/path/${i}/raw_fastq
    trim_fastq_dir=/path/${i}/nanofilt
    for file in $raw_fastq_dir/*.fastq; do
        sample_id1="${file##*/}"
        if [[ "$sample_id1" == *_es.fastq ]]; then
            location="Spain"
        elif [[ "$sample_id1" == *_au.fastq ]]; then
            location="Australia"
        fi
        if [[ "$sample_id1" == *lsk*.fastq ]]; then
            sequencing_kit="Ligation_kit"
        elif [[ "$sample_id1" == *rbk*.fastq ]]; then
            sequencing_kit="Rapid_kit"
        fi
        if [[ "$sample_id1" == *_fa_*.fastq ]]; then
            mode="FAST"
        elif [[ "$sample_id1" == *_hac_*.fastq ]]; then
            mode="HAC"
        elif [[ "$sample_id1" == *_sup_*.fastq ]]; then
            mode="SUP"
        fi
        if [[ "$sample_id1" == *powerfecal*.fastq ]]; then
            extraction_kit="PowerFecal"
        elif [[ "$sample_id1" == *powersoil*.fastq ]]; then
            extraction_kit="Powersoil"
        fi
        sample_id2="${sample_id1%%.*}"
        before_reads=$(cat $file | paste - - - - | cut -f 2 | tr -d '\n' | wc -c)
        after_reads=$(cat $trim_fastq_dir/$sample_id1 | paste - - - - | cut -f 2 | tr -d '\n' | wc -c)
        echo -e "$sample_id2\t$extraction_kit\t$sequencing_kit\t$mode\t$location\t$before_reads\t$after_reads\t$trim_reads" >> $stats_dir/rumen_base_num_stats_sup.tsv
        echo "${sample_id1} is finished"
    done
done

### calculate base number for dna data
echo -e "sample_id\textraction_kit\tsequencing_kit\tbasecall_mode\tlocation\traw_bases\tafter_bases\ttrim_bases" > rumen_base_num_stats_sup_dna.tsv  
for i in fa hac sup; do
    raw_fastq_dir=/path/${i}/raw_fastq
    trim_fastq_dir=/path/${i}/nanofilt
    for file in $raw_fastq_dir/*.fastq; do
        sample_id1="${file##*/}"
        if [[ "$sample_id1" == *_es.fastq ]]; then
            location="Spain"
        elif [[ "$sample_id1" == *_au.fastq ]]; then
            location="Australia"
        fi
        if [[ "$sample_id1" == *lsk*.fastq ]]; then
            sequencing_kit="Ligation_kit"
        elif [[ "$sample_id1" == *rbk*.fastq ]]; then
            sequencing_kit="Rapid_kit"
        fi
        if [[ "$sample_id1" == *_fa_*.fastq ]]; then
            mode="FAST"
        elif [[ "$sample_id1" == *_hac_*.fastq ]]; then
            mode="HAC"
        elif [[ "$sample_id1" == *_sup_*.fastq ]]; then
            mode="SUP"
        fi
        if [[ "$sample_id1" == *dneasy*.fastq ]]; then
            extraction_kit="Dneasy"
        elif [[ "$sample_id1" == *puregene*.fastq ]]; then
            extraction_kit="Puregene"
        fi
        sample_id2="${sample_id1%%.*}"
        before_reads=$(cat $file | paste - - - - | cut -f 2 | tr -d '\n' | wc -c)
        after_reads=$(cat $trim_fastq_dir/$sample_id1 | paste - - - - | cut -f 2 | tr -d '\n' | wc -c)
        echo -e "$sample_id2\t$extraction_kit\t$sequencing_kit\t$mode\t$location\t$before_reads\t$after_reads\t$trim_reads" >> $stats_dir/rumen_base_num_stats_sup_dna.tsv
        echo "${sample_id1} is finished"
    done
done
