#!/bin/bash -l
#SBATCH --job-name="rumen_metaflye"
#SBATCH -o rumen_metaflye.o
#SBATCH -e rumen_metaflye.e

##############################################################
results=/path/
nanofilt_folder=/path/
subsample_folder=/path/
flye_folder=/path/

##############################################################
## load necessary module
module load anaconda3
module load flye/2.9-gcc-10.3.0

##############################################################
## subsample the data
source activate rasusa
cd $nanofilt_folder

for file in *.fastq;
do
	rasusa --input $file --bases 0.19gb -s 1500 -o $subsample_folder/${file%%.*}.fastq
done

##############################################################
## flye assembly using meta flag
cd $subsample_folder

for file in *.fastq
do
	flye --nano-hq $file --meta --threads 20 --out-dir $flye_folder/${file%%.*}/
done