#!/bin/bash -l
#SBATCH --job-name="TSU_30_interation_site_extraction"
#SBATCH -o TSU_30_interation_site_extraction.o
#SBATCH -e TSU_30_interation_site_extraction.e

#######################################################
module load anaconda3
module load samtools

#######################################################
lsk_bed=/path/
rbk_bed=/path/

lsk_bed_subset=/path/
rbk_bed_subset=/path/

insertion_folder=/path/
#######################################################
## extract insertion sites from bed files based on the direction sign in column 6 ($6)
cd $lsk_bed
for file in *.bed;
do
    awk 'BEGIN{FS=OFS="\t"} $1 ~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|X)$/ {if ($6=="+"){print $1, $2} else {print $1, $3}}' $file > $lsk_bed_subset/subset_${file%%.*}.bed
done

cd $rbk_bed
for file in *.bed;
do
    awk 'BEGIN{FS=OFS="\t"} $1 ~ /^(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|X)$/ {if ($6=="+"){print $1, $2} else {print $1, $3}}' $file > $rbk_bed_subset/subset_${file%%.*}.bed
done

#######################################################
## extract prefix of bed files
cd $lsk_bed_subset

output_file=lsk_prefix.tsv
for file in *LSK*; do
  if [[ -f "$file" ]]; then
    prefix="${file%_*.bed}"
    echo "$prefix" >> "$output_file"
  fi
done
sort -u -o "$output_file" "$output_file"
cat lsk_prefix.tsv | while read -r prefix;do cat ${prefix}_plus.bed ${prefix}_minus.bed > ${prefix}.bed;done

rm *plus.bed *minus.bed

cd $rbk_bed_subset

output_file=rbk_prefix.tsv
for file in *RBK*; do
  if [[ -f "$file" ]]; then
    prefix="${file%_*.bed}"
    echo "$prefix" >> "$output_file"
  fi
done
sort -u -o "$output_file" "$output_file"
cat rbk_prefix.tsv | while read -r prefix;do cat ${prefix}_plus.bed ${prefix}_minus.bed > ${prefix}.bed;done

rm *plus.bed *minus.bed

#######################################################
## change the name of bed file and make meta-tsv files
cd $lsk_bed_subset
echo -e "sample_ID\treplicate" > file_name.tsv
for file in *.bed; do echo ${file%%.*} | sort | uniq >> name.tsv; done
awk 'BEGIN{FS=OFS="\t"} {print $0, "LSK114_R"NR}' name.tsv >> file_name.tsv
tail -n +2 file_name.tsv | while IFS=$'\t' read -r old new;do mv "${old}.bed" "${new}.bed";done
for file in *.bed;
do
    filename=${file%%.*}
    kit="Ligation_kit"
    awk 'BEGIN{FS=OFS="\t"} {print $1, $2, filename, kit}' filename="$filename" kit="$kit" $file > tmp && mv tmp $file
done
cat *.bed > lsk_insertion_site.tsv
mv lsk_insertion_site.tsv $insertion_folder

cd $rbk_bed_subset
echo -e "sample_ID\treplicate" > file_name.tsv
for file in *.bed; do echo ${file%%.*} | sort | uniq >> name.tsv; done
awk 'BEGIN{FS=OFS="\t"} {print $0, "RBK110_R"NR}' name.tsv >> file_name.tsv
tail -n +2 file_name.tsv | while IFS=$'\t' read -r old new;do mv "${old}.bed" "${new}.bed";done
for file in *.bed;
do
    filename=${file%%.*}
    kit="Rapid_kit"
    awk 'BEGIN{FS=OFS="\t"} {print $1, $2, filename, kit}' filename="$filename" kit="$kit" $file > tmp && mv tmp $file
done
cat *.bed > rbk_insertion_site.tsv
mv rbk_insertion_site.tsv $insertion_folder

#######################################################
## separate the meta-tsv file into different chromosome folder
cd $insertion_folder
cat lsk_insertion_site.tsv rbk_insertion_site.tsv > lsk_rbk_insertion_site.tsv

for i in {1..29} X;
do
    value="$insertion_folder/chr_${i}"
    echo "now is processing chromosome$i"
    awk -v chromosome="$i" 'BEGIN{FS="\t";OFS="\t"} $1==chromosome {print $0}' lsk_rbk_insertion_site.tsv > "${value}"/lsk_rbk_insertion_site_chr${i}.tsv
done












